-- ============================================================
-- Fitur lanjutan: foto album (Storage), manajemen pengguna, riwayat, nomor HP pada iuran.
-- Aman dijalankan berulang (idempotent).
-- ============================================================
create table if not exists photos(id bigint generated by default as identity primary key, album_id bigint not null references albums(id) on delete cascade, path text not null unique, caption text, created_at timestamptz not null default now());
alter table photos enable row level security;
drop policy if exists "baca" on photos;        create policy "baca" on photos for select to authenticated using (true);
drop policy if exists "admin tulis" on photos; create policy "admin tulis" on photos for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Bucket FOTO PRIVAT (hanya pengguna login yang bisa melihat; hanya admin yang boleh unggah/hapus). Maks 5 MB, jpeg/png/webp.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('photos','photos',false,5242880,array['image/jpeg','image/png','image/webp'])
 on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
drop policy if exists "fh baca foto" on storage.objects;   create policy "fh baca foto" on storage.objects for select to authenticated using (bucket_id='photos');
drop policy if exists "fh unggah foto" on storage.objects; create policy "fh unggah foto" on storage.objects for insert to authenticated with check (bucket_id='photos' and public.is_admin());
drop policy if exists "fh hapus foto" on storage.objects;  create policy "fh hapus foto" on storage.objects for delete to authenticated using (bucket_id='photos' and public.is_admin());

-- Daftar iuran kini menyertakan nomor HP (untuk pengingat WhatsApp)
create or replace function public.get_payments(p_period text default null) returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('period',x.p,'iuran',cfg('iuran')::int,'rows',coalesce((select jsonb_agg(jsonb_build_object('member_id',m.id,'name',m.name,'relation',m.relation,'phone',m.phone,'pid',py.id,'amount',py.amount,'paid_at',py.paid_at) order by m.name) from members m left join payments py on py.member_id=m.id and py.period=x.p where m.active=1),'[]'::jsonb))
 from (select coalesce(p_period,cur_period()) p) x $$;

-- Manajemen pengguna (khusus admin). Email dibaca dari auth.users lewat fungsi, tidak dibuka ke semua orang.
create or replace function public.list_users() returns jsonb language plpgsql stable security definer set search_path=public as $$
begin perform need_admin();
 return coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'email',u.email,'role',p.role) order by p.role,p.name) from profiles p join auth.users u on u.id=p.id),'[]'::jsonb); end $$;
create or replace function public.set_role(p_id uuid,p_role text) returns void language plpgsql security definer set search_path=public as $$
begin perform need_admin();
 if p_role not in('admin','viewer') then raise exception 'Peran tidak valid'; end if;
 if p_role='viewer' and not exists(select 1 from profiles where role='admin' and id<>p_id) then raise exception 'Harus ada minimal satu admin'; end if;
 update profiles set role=p_role where id=p_id; perform log_act('⚙','Peran pengguna diubah',p_role); end $$;

revoke execute on function public.list_users(), public.set_role(uuid,text), public.get_payments(text) from public, anon;
grant execute on function public.list_users(), public.set_role(uuid,text), public.get_payments(text) to authenticated;
