-- ============================================================
-- FamilyHub — skema Supabase (jalankan di SQL Editor, sekali saja)
-- ============================================================
create table profiles(id uuid primary key references auth.users(id) on delete cascade, name text not null, role text not null default 'viewer' check(role in('admin','viewer')));
create table settings(k text primary key, v text not null);
insert into settings values('iuran','350000'),('cycle','1');
create table members(id bigint generated by default as identity primary key, name text not null, relation text, generation int not null default 1, parent_id bigint references members(id) on delete set null, phone text, joined int, active int not null default 1);
create table payments(id bigint generated by default as identity primary key, member_id bigint not null references members(id) on delete cascade, period text not null check(period ~ '^\d{4}-\d{2}$'), amount int not null, paid_at timestamptz not null default now(), unique(member_id,period));
create table transactions(id bigint generated by default as identity primary key, date date not null, description text not null, type text not null check(type in('masuk','keluar')), amount bigint not null check(amount>0), payment_id bigint references payments(id) on delete cascade);
create table events(id bigint generated by default as identity primary key, date date not null, time text, title text not null, location text, status text not null default 'Terjadwal');
create table announcements(id bigint generated by default as identity primary key, title text not null, body text, date date not null default current_date, author text);
create table albums(id bigint generated by default as identity primary key, title text not null, emoji text default '📸');
create table draws(id bigint generated by default as identity primary key, cycle int not null, period text not null unique, at timestamptz not null default now(), participants text, winner_id bigint not null references members(id) on delete restrict, winner_name text not null, proof text);
create table activity(id bigint generated by default as identity primary key, icon text, text text, detail text, at timestamptz not null default now());

-- ---------- Helper ----------
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce((select role='admin' from profiles where id=auth.uid()),false) $$;
create function public.cur_period() returns text language sql stable as $$ select to_char(now() at time zone 'Asia/Jakarta','YYYY-MM') $$;
create function public.cfg(text) returns text language sql stable security definer set search_path=public as $$ select v from settings where k=$1 $$;
create function public.log_act(i text,t text,d text default '') returns void language sql security definer set search_path=public as $$ insert into activity(icon,text,detail) values(i,t,d) $$;
create function public.need_admin() returns void language plpgsql stable as $$ begin if not public.is_admin() then raise exception 'Hanya admin yang boleh mengubah data'; end if; end $$;

-- Akun baru otomatis punya profil. Pengguna PERTAMA yang mendaftar menjadi admin.
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into profiles(id,name,role) values(new.id, coalesce(nullif(new.raw_user_meta_data->>'name',''),split_part(new.email,'@',1)), case when exists(select 1 from profiles) then 'viewer' else 'admin' end); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create function public.trg_log() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into activity(icon,text,detail) values('＋',initcap(tg_table_name)||' baru ditambahkan',coalesce(to_jsonb(new)->>'name',to_jsonb(new)->>'title','')); return new; end $$;
create trigger log_members after insert on members for each row execute function public.trg_log();
create trigger log_events after insert on events for each row execute function public.trg_log();
create trigger log_ann after insert on announcements for each row execute function public.trg_log();
create trigger log_albums after insert on albums for each row execute function public.trg_log();

-- Membuat profil otomatis bila belum ada (mis. akun dibuat sebelum skema dijalankan). Pengguna pertama = admin.
create function public.ensure_profile() returns jsonb language plpgsql security definer set search_path=public as $$
declare u auth.users; p profiles;
begin
 if auth.uid() is null then raise exception 'Silakan login'; end if;
 select * into p from profiles where id=auth.uid();
 if not found then
  select * into u from auth.users where id=auth.uid();
  insert into profiles(id,name,role) values(u.id, coalesce(nullif(u.raw_user_meta_data->>'name',''),split_part(u.email,'@',1)), case when exists(select 1 from profiles) then 'viewer' else 'admin' end) returning * into p;
 end if;
 return jsonb_build_object('name',p.name,'role',p.role);
end $$;

-- ---------- Iuran ----------
create function public.get_payments(p_period text default null) returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('period',x.p,'iuran',cfg('iuran')::int,'rows',coalesce((select jsonb_agg(jsonb_build_object('member_id',m.id,'name',m.name,'relation',m.relation,'pid',py.id,'amount',py.amount,'paid_at',py.paid_at) order by m.name) from members m left join payments py on py.member_id=m.id and py.period=x.p where m.active=1),'[]'::jsonb))
 from (select coalesce(p_period,cur_period()) p) x $$;

create function public.record_payment(p_member bigint,p_period text) returns void language plpgsql security definer set search_path=public as $$
declare m members; amt int; pid bigint;
begin
 perform need_admin();
 select * into m from members where id=p_member and active=1; if not found then raise exception 'Anggota tidak ditemukan atau nonaktif'; end if;
 if p_period !~ '^\d{4}-\d{2}$' then raise exception 'Periode tidak valid'; end if;
 if exists(select 1 from payments where member_id=p_member and period=p_period) then raise exception 'Iuran periode ini sudah tercatat'; end if;
 amt:=cfg('iuran')::int;
 insert into payments(member_id,period,amount) values(p_member,p_period,amt) returning id into pid;
 insert into transactions(date,description,type,amount,payment_id) values((now() at time zone 'Asia/Jakarta')::date,'Iuran '||p_period||' - '||m.name,'masuk',amt,pid);
 perform log_act('✓',m.name||' membayar iuran','Rp '||to_char(amt,'FM999G999G999'));
end $$;

create function public.void_payment(p_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin perform need_admin(); delete from payments where id=p_id; end $$;   -- transaksi terkait ikut terhapus (cascade)

create function public.set_iuran(p int) returns void language plpgsql security definer set search_path=public as $$
begin perform need_admin(); if p is null or p<=0 then raise exception 'Nominal iuran tidak valid'; end if; update settings set v=p::text where k='iuran'; end $$;

-- ---------- Pengocokan digital ----------
create function public.eligible_members(p text) returns table(id bigint,name text) language sql stable security definer set search_path=public as $$
 select m.id,m.name from members m where m.active=1 and exists(select 1 from payments y where y.member_id=m.id and y.period=p)
 and not exists(select 1 from draws d where d.winner_id=m.id and d.cycle=cfg('cycle')::int) order by m.id $$;

create function public.draw_state() returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('period',cur_period(),'cycle',cfg('cycle')::int,
  'eligible',coalesce((select jsonb_agg(to_jsonb(e)) from eligible_members(cur_period()) e),'[]'::jsonb),
  'unpaid',(select count(*) from members m where m.active=1 and not exists(select 1 from payments y where y.member_id=m.id and y.period=cur_period())),
  'history',coalesce((select jsonb_agg(to_jsonb(d) order by d.id desc) from draws d),'[]'::jsonb)) $$;

create function public.run_draw() returns jsonb language plpgsql security definer set search_path=public as $$
declare p text:=cur_period(); w record; ids text; n int; proof text; at_ timestamptz:=now();
begin
 perform need_admin();
 if exists(select 1 from draws where period=p) then raise exception 'Pengundian periode % sudah dilakukan',p; end if;
 select count(*),(to_jsonb(array_agg(e.id order by e.id)))::text into n,ids from eligible_members(p) e;
 if n=0 then raise exception 'Tidak ada peserta eligible (belum bayar atau semua sudah menang di siklus ini)'; end if;
 select e.id,e.name into w from eligible_members(p) e order by gen_random_uuid() limit 1;  -- acak kriptografis (UUID v4)
 proof:=encode(sha256(convert_to(p||'|'||at_::text||'|'||ids||'|'||w.id||'|'||gen_random_uuid()::text,'UTF8')),'hex');
 insert into draws(cycle,period,at,participants,winner_id,winner_name,proof) values(cfg('cycle')::int,p,at_,ids,w.id,w.name,proof);
 perform log_act('⚡','Pemenang arisan '||p||': '||w.name,n||' peserta');
 return jsonb_build_object('winner',jsonb_build_object('id',w.id,'name',w.name),'at',at_,'proof',proof);
end $$;

create function public.new_cycle() returns void language plpgsql security definer set search_path=public as $$
begin perform need_admin(); update settings set v=(v::int+1)::text where k='cycle'; perform log_act('↻','Siklus arisan baru dimulai'); end $$;

-- ---------- Dashboard & laporan ----------
create function public.dashboard() returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object(
  'saldo',coalesce((select sum(case when type='masuk' then amount else -amount end) from transactions),0),
  'masuk',coalesce((select sum(amount) from transactions where type='masuk'),0),
  'keluar',coalesce((select sum(amount) from transactions where type='keluar'),0),
  'n',(select count(*) from transactions),
  'members',(select count(*) from members where active=1),
  'paid',(select count(*) from payments y join members m on m.id=y.member_id where y.period=cur_period() and m.active=1),
  'period',cur_period(),'iuran',cfg('iuran')::int,
  'cashflow',coalesce((select jsonb_agg(c order by c.m) from (select to_char(date,'YYYY-MM') m,sum(case when type='masuk' then amount else 0 end) masuk,sum(case when type='keluar' then amount else 0 end) keluar from transactions group by 1 order by 1 desc limit 6) c),'[]'::jsonb),
  'next',(select to_jsonb(e) from events e where e.date>=(now() at time zone 'Asia/Jakarta')::date order by e.date limit 1),
  'activity',coalesce((select jsonb_agg(to_jsonb(a) order by a.id desc) from (select * from activity order by id desc limit 5) a),'[]'::jsonb),
  'recent',coalesce((select jsonb_agg(to_jsonb(r) order by r.id desc) from (select id,name,relation,generation from members where active=1 order by id desc limit 4) r),'[]'::jsonb)) $$;

create function public.report() returns jsonb language sql stable security definer set search_path=public as $$
 select coalesce(jsonb_agg(to_jsonb(r) order by r.m desc),'[]'::jsonb) from (
  select m,masuk,keluar,sum(masuk-keluar) over(order by m) saldo from (
   select to_char(date,'YYYY-MM') m,sum(case when type='masuk' then amount else 0 end) masuk,sum(case when type='keluar' then amount else 0 end) keluar from transactions group by 1) t) r $$;

-- ---------- Keamanan: Row Level Security ----------
do $$ declare t text; begin
 foreach t in array array['profiles','settings','members','payments','transactions','events','announcements','albums','draws','activity'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('create policy "baca" on public.%I for select to authenticated using (true)',t);
 end loop;
 foreach t in array array['members','transactions','events','announcements','albums'] loop
  execute format('create policy "admin tulis" on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',t);
 end loop;
end $$;
create policy "admin ubah peran" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Hanya pengguna login yang boleh memanggil fungsi; helper internal ditutup.
revoke execute on all functions in schema public from public, anon;
grant execute on all functions in schema public to authenticated;
revoke execute on function public.log_act(text,text,text), public.handle_new_user(), public.trg_log() from authenticated;

-- ============================================================
-- Fitur lanjutan: foto album (Storage), manajemen pengguna, riwayat, nomor HP pada iuran.
-- Aman dijalankan berulang (idempotent).
-- ============================================================
create table if not exists photos(id bigint generated by default as identity primary key, album_id bigint not null references albums(id) on delete cascade, path text not null unique, caption text, created_at timestamptz not null default now());
alter table photos enable row level security;
drop policy if exists "baca" on photos;        create policy "baca" on photos for select to authenticated using (true);
drop policy if exists "admin tulis" on photos; create policy "admin tulis" on photos for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Bucket FOTO PRIVAT (hanya pengguna login yang bisa melihat; hanya admin yang boleh unggah/hapus). Maks 5 MB, jpeg/png/webp.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('photos','photos',false,5242880,array['image/jpeg','image/png','image/webp'])
 on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
drop policy if exists "fh baca foto" on storage.objects;   create policy "fh baca foto" on storage.objects for select to authenticated using (bucket_id='photos');
drop policy if exists "fh unggah foto" on storage.objects; create policy "fh unggah foto" on storage.objects for insert to authenticated with check (bucket_id='photos' and public.is_admin());
drop policy if exists "fh hapus foto" on storage.objects;  create policy "fh hapus foto" on storage.objects for delete to authenticated using (bucket_id='photos' and public.is_admin());

-- Daftar iuran kini menyertakan nomor HP (untuk pengingat WhatsApp)
create or replace function public.get_payments(p_period text default null) returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('period',x.p,'iuran',cfg('iuran')::int,'rows',coalesce((select jsonb_agg(jsonb_build_object('member_id',m.id,'name',m.name,'relation',m.relation,'phone',m.phone,'pid',py.id,'amount',py.amount,'paid_at',py.paid_at) order by m.name) from members m left join payments py on py.member_id=m.id and py.period=x.p where m.active=1),'[]'::jsonb))
 from (select coalesce(p_period,cur_period()) p) x $$;

-- Manajemen pengguna (khusus admin). Email dibaca dari auth.users lewat fungsi, tidak dibuka ke semua orang.
create or replace function public.list_users() returns jsonb language plpgsql stable security definer set search_path=public as $$
begin perform need_admin();
 return coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'email',u.email,'role',p.role) order by p.role,p.name) from profiles p join auth.users u on u.id=p.id),'[]'::jsonb); end $$;
create or replace function public.set_role(p_id uuid,p_role text) returns void language plpgsql security definer set search_path=public as $$
begin perform need_admin();
 if p_role not in('admin','viewer') then raise exception 'Peran tidak valid'; end if;
 if p_role='viewer' and not exists(select 1 from profiles where role='admin' and id<>p_id) then raise exception 'Harus ada minimal satu admin'; end if;
 update profiles set role=p_role where id=p_id; perform log_act('⚙','Peran pengguna diubah',p_role); end $$;

revoke execute on function public.list_users(), public.set_role(uuid,text), public.get_payments(text) from public, anon;
grant execute on function public.list_users(), public.set_role(uuid,text), public.get_payments(text) to authenticated;

-- ============================================================
-- v2.3 Silsilah skala besar: jenis kelamin, pasangan, tahun lahir/wafat, generasi otomatis, impor massal.
-- Aman dijalankan berulang (idempotent).
-- ============================================================
alter table public.members add column if not exists gender text;
alter table public.members add column if not exists spouse_id bigint references public.members(id) on delete set null;
alter table public.members add column if not exists spouse_status text not null default 'menikah';
alter table public.members add column if not exists birth_year int;
alter table public.members add column if not exists death_year int;
do $$ begin
 if not exists(select 1 from pg_constraint where conname='members_gender_chk') then alter table public.members add constraint members_gender_chk check (gender in ('L','P')); end if;
 if not exists(select 1 from pg_constraint where conname='members_spouse_status_chk') then alter table public.members add constraint members_spouse_status_chk check (spouse_status in ('menikah','cerai')); end if;
 if not exists(select 1 from pg_constraint where conname='members_years_chk') then alter table public.members add constraint members_years_chk check ((birth_year is null or birth_year between 1700 and 2200) and (death_year is null or death_year between 1700 and 2200) and (birth_year is null or death_year is null or death_year>=birth_year)); end if;
 if not exists(select 1 from pg_constraint where conname='members_self_chk') then alter table public.members add constraint members_self_chk check (parent_id is distinct from id and spouse_id is distinct from id); end if;
end $$;
create index if not exists members_parent_idx on public.members(parent_id);
create index if not exists members_spouse_idx on public.members(spouse_id);

-- Generasi dihitung otomatis dari hubungan: akar = 1, anak = orang tua + 1, pasangan yang masuk keluarga mengikuti generasi pasangannya.
create or replace function public.recalc_generations() returns void language plpgsql security definer set search_path=public as $$
begin
 with recursive t(id,g) as (
   select m.id,1 from members m where m.parent_id is null
     and not exists(select 1 from members y where y.parent_id is not null and (m.spouse_id=y.id or y.spouse_id=m.id))
   union
   select c.id, t.g+(case when c.parent_id=t.id then 1 else 0 end)
   from t join members c on c.parent_id=t.id
        or (c.parent_id is null and (c.spouse_id=t.id or exists(select 1 from members z where z.id=t.id and z.spouse_id=c.id)))
   where t.g<40)
 update members x set generation=s.g from (select id,min(g) g from t group by id) s where x.id=s.id and x.generation is distinct from s.g;
end $$;
create or replace function public.trg_recalc() returns trigger language plpgsql security definer set search_path=public as $$
begin if coalesce(current_setting('fh.skip_recalc',true),'')<>'1' then perform public.recalc_generations(); end if; return null; end $$;
drop trigger if exists members_recalc on public.members;
create trigger members_recalc after insert or delete or update of parent_id, spouse_id on public.members for each statement execute function public.trg_recalc();

-- Impor massal (khusus admin, atomik: gagal satu baris = batal semua). Tautan antar baris memakai kolom "kode".
create or replace function public.import_members(p jsonb) returns int language plpgsql security definer set search_path=public as $$
declare r record; ids jsonb:='{}'::jsonb; arr bigint[]:='{}'; nid bigint; n int:=0; k text; o text; s text;
begin
 perform need_admin();
 if p is null or jsonb_typeof(p)<>'array' then raise exception 'Format data impor tidak valid'; end if;
 if jsonb_array_length(p)>2000 then raise exception 'Maksimal 2000 baris per impor'; end if;
 perform set_config('fh.skip_recalc','1',true);
 for r in select e.value v, e.ordinality i from jsonb_array_elements(p) with ordinality e loop
  begin
   if coalesce(trim(r.v->>'nama'),'')='' then raise exception 'nama kosong'; end if;
   k:=nullif(trim(r.v->>'kode'),'');
   if k is not null and ids ? k then raise exception 'kode "%" dipakai dua kali',k; end if;
   insert into members(name,gender,relation,birth_year,death_year,phone,spouse_status)
   values(trim(r.v->>'nama'),nullif(upper(trim(r.v->>'gender')),''),nullif(trim(r.v->>'hubungan'),''),nullif(trim(r.v->>'lahir'),'')::int,nullif(trim(r.v->>'wafat'),'')::int,nullif(trim(r.v->>'telepon'),''),coalesce(nullif(lower(trim(r.v->>'status_pasangan')),''),'menikah'))
   returning id into nid;
  exception when others then raise exception 'Baris %: %',r.i+1,sqlerrm; end;
  arr:=arr||nid; n:=n+1; if k is not null then ids:=ids||jsonb_build_object(k,nid); end if;
 end loop;
 for r in select e.value v, e.ordinality i from jsonb_array_elements(p) with ordinality e loop
  o:=nullif(trim(r.v->>'kode_ortu'),''); s:=nullif(trim(r.v->>'kode_pasangan'),'');
  if o is not null then
    if not ids ? o then raise exception 'Baris %: kode_ortu "%" tidak ditemukan',r.i+1,o; end if;
    if (ids->>o)::bigint=arr[r.i] then raise exception 'Baris %: orang tua tidak boleh diri sendiri',r.i+1; end if;
    update members set parent_id=(ids->>o)::bigint where id=arr[r.i];
  end if;
  if s is not null then
    if not ids ? s then raise exception 'Baris %: kode_pasangan "%" tidak ditemukan',r.i+1,s; end if;
    if (ids->>s)::bigint=arr[r.i] then raise exception 'Baris %: pasangan tidak boleh diri sendiri',r.i+1; end if;
    update members set spouse_id=(ids->>s)::bigint where id=arr[r.i];
  end if;
 end loop;
 perform set_config('fh.skip_recalc','0',true);
 perform public.recalc_generations();
 perform log_act('⬆','Impor anggota dari CSV',n||' orang');
 return n;
end $$;

revoke execute on function public.recalc_generations(), public.trg_recalc() from public, anon, authenticated;
revoke execute on function public.import_members(jsonb) from public, anon;
grant execute on function public.import_members(jsonb) to authenticated;
select public.recalc_generations();

-- ============================================================
-- v2.4 Foto profil anggota + status pernikahan per orang.
-- Aman dijalankan berulang (idempotent).
-- ============================================================
alter table public.members add column if not exists marital_status text;   -- belum_menikah | menikah | cerai | cerai_mati
alter table public.members add column if not exists photo_path text;        -- awalan berkas di bucket "photos": <path>_s.jpg (kecil) & <path>_l.jpg (besar)
do $$ begin
 if not exists(select 1 from pg_constraint where conname='members_marital_chk') then
  alter table public.members add constraint members_marital_chk check (marital_status in ('belum_menikah','menikah','cerai','cerai_mati'));
 end if;
end $$;

-- Impor massal kini menerima kolom marital_status
create or replace function public.import_members(p jsonb) returns int language plpgsql security definer set search_path=public as $$
declare r record; ids jsonb:='{}'::jsonb; arr bigint[]:='{}'; nid bigint; n int:=0; k text; o text; s text;
begin
 perform need_admin();
 if p is null or jsonb_typeof(p)<>'array' then raise exception 'Format data impor tidak valid'; end if;
 if jsonb_array_length(p)>2000 then raise exception 'Maksimal 2000 baris per impor'; end if;
 perform set_config('fh.skip_recalc','1',true);
 for r in select e.value v, e.ordinality i from jsonb_array_elements(p) with ordinality e loop
  begin
   if coalesce(trim(r.v->>'nama'),'')='' then raise exception 'nama kosong'; end if;
   k:=nullif(trim(r.v->>'kode'),'');
   if k is not null and ids ? k then raise exception 'kode "%" dipakai dua kali',k; end if;
   insert into members(name,gender,relation,birth_year,death_year,phone,spouse_status,marital_status)
   values(trim(r.v->>'nama'),nullif(upper(trim(r.v->>'gender')),''),nullif(trim(r.v->>'hubungan'),''),nullif(trim(r.v->>'lahir'),'')::int,nullif(trim(r.v->>'wafat'),'')::int,nullif(trim(r.v->>'telepon'),''),coalesce(nullif(lower(trim(r.v->>'status_pasangan')),''),'menikah'),nullif(lower(trim(r.v->>'marital_status')),''))
   returning id into nid;
  exception when others then raise exception 'Baris %: %',r.i+1,sqlerrm; end;
  arr:=arr||nid; n:=n+1; if k is not null then ids:=ids||jsonb_build_object(k,nid); end if;
 end loop;
 for r in select e.value v, e.ordinality i from jsonb_array_elements(p) with ordinality e loop
  o:=nullif(trim(r.v->>'kode_ortu'),''); s:=nullif(trim(r.v->>'kode_pasangan'),'');
  if o is not null then
    if not ids ? o then raise exception 'Baris %: kode_ortu "%" tidak ditemukan',r.i+1,o; end if;
    if (ids->>o)::bigint=arr[r.i] then raise exception 'Baris %: orang tua tidak boleh diri sendiri',r.i+1; end if;
    update members set parent_id=(ids->>o)::bigint where id=arr[r.i];
  end if;
  if s is not null then
    if not ids ? s then raise exception 'Baris %: kode_pasangan "%" tidak ditemukan',r.i+1,s; end if;
    if (ids->>s)::bigint=arr[r.i] then raise exception 'Baris %: pasangan tidak boleh diri sendiri',r.i+1; end if;
    update members set spouse_id=(ids->>s)::bigint where id=arr[r.i];
  end if;
 end loop;
 perform set_config('fh.skip_recalc','0',true);
 perform public.recalc_generations();
 perform log_act('⬆','Impor anggota dari CSV',n||' orang');
 return n;
end $$;

-- Bantuan sekali-klik (admin): anggota tanpa pasangan tercatat & status kosong -> "Belum menikah". Mengembalikan jumlah yang diubah.
create or replace function public.fill_marital_status() returns int language plpgsql security definer set search_path=public as $$
declare n int;
begin
 perform need_admin();
 update members m set marital_status='belum_menikah'
  where m.marital_status is null and m.spouse_id is null and not exists(select 1 from members x where x.spouse_id=m.id);
 get diagnostics n = row_count; return n;
end $$;
revoke execute on function public.import_members(jsonb), public.fill_marital_status() from public, anon;
grant execute on function public.import_members(jsonb), public.fill_marital_status() to authenticated;
