-- OPSIONAL: data contoh (jalankan setelah schema.sql). Lewati jika ingin mulai dari kosong.
insert into members(name,relation,generation,joined) values ('H. Santoso','Kakek',1,2020),('Budi Santoso','Anak',2,2020),('Rina Novitasari','Anak',2,2020),('Andi Pratama','Cucu',3,2024),('Maya Sari','Cucu',3,2024),('Dimas Santoso','Cucu',3,2024),('Nadia Santoso','Cucu',3,2024);
update members c set parent_id=(select id from members p where p.name=v.par) from (values ('Budi Santoso','H. Santoso'),('Rina Novitasari','H. Santoso'),('Andi Pratama','Budi Santoso'),('Maya Sari','Budi Santoso'),('Dimas Santoso','Rina Novitasari'),('Nadia Santoso','Rina Novitasari')) v(child,par) where c.name=v.child;
with p as (insert into payments(member_id,period,amount,paid_at) select id,public.cur_period(),350000,now()-random()*interval '5 days' from members where name<>'Dimas Santoso' returning id,member_id)
insert into transactions(date,description,type,amount,payment_id) select current_date,'Iuran '||public.cur_period()||' - '||m.name,'masuk',350000,p.id from p join members m on m.id=p.member_id;
insert into transactions(date,description,type,amount) values (current_date-120,'Saldo kas awal','masuk',6000000),(current_date-40,'Konsumsi arisan','keluar',1500000),(current_date-20,'Iuran bulan lalu (rekap)','masuk',2100000),(current_date-12,'Dekorasi & konsumsi','keluar',2050000),(current_date-4,'Sewa tempat acara','keluar',1200000);
insert into events(date,time,title,location) values (current_date+6,'16:00','Arisan Keluarga Besar Santoso','Rumah Bu Rina'),(current_date+18,'18:00','Ulang Tahun Pak Budi','Surabaya');
insert into announcements(title,body,author) values ('Arisan akan dilaksanakan pekan depan','Mohon hadir tepat waktu pukul 16:00 WIB.','Admin'),('Rekap iuran bulan lalu telah ditutup','','Admin');
insert into albums(emoji,title) values ('📸','Arisan Bulan Lalu'),('🎉','Lebaran Keluarga'),('👨‍👩‍👧‍👦','Family Gathering'),('🌿','Liburan Keluarga');
insert into draws(cycle,period,at,participants,winner_id,winner_name,proof) select 1,to_char(now() at time zone 'Asia/Jakarta' - interval '1 month','YYYY-MM'),now()-interval '30 days','[1,2,3,4,5,6,7]',id,name,'seed' from members where name='Rina Novitasari';
